"""
Agent 3: Tactical Classifier
Translates computed metrics into tactical labels (pressing style,
buildup pattern, formation shape) using structured rules + LLM reasoning.

This is the "judgmental skill" that separates Pitch Verdict from a generic
AI tool. The classifications are grounded in real metrics — not vibes.
"""

from dataclasses import dataclass, field
from typing import List, Dict, Optional
from agents.phase_segmenter import MatchPhase, MatchSegmentation, PhaseSegmenterAgent


@dataclass
class TacticalProfile:
    """
    Complete tactical assessment for one team in one phase.
    All labels are grounded in computed metrics.
    """
    team: str
    phase_name: str
    start_minute: int
    end_minute: int

    # Core labels
    pressing_style: str = ""       # "High Press", "Mid-Block", "Deep Block"
    buildup_pattern: str = ""      # "Short/Patient", "Direct", "Mixed"
    territorial_dominance: str = ""  # "Dominant", "Balanced", "Subdued"
    xg_efficiency: str = ""        # "Clinical", "Average", "Wasteful"

    # Supporting metrics (raw numbers)
    ppda: float = 0.0
    possession_pct: float = 0.0
    pass_completion_pct: float = 0.0
    xg: float = 0.0
    shots: int = 0
    pressures: int = 0

    # Narrative insight (generated by LLM, verified by Verifier)
    tactical_narrative: str = ""

    def to_dict(self) -> dict:
        return {
            'team': self.team,
            'phase': self.phase_name,
            'minutes': f"{self.start_minute}'–{self.end_minute}'",
            'pressing_style': self.pressing_style,
            'buildup_pattern': self.buildup_pattern,
            'territorial_dominance': self.territorial_dominance,
            'xg_efficiency': self.xg_efficiency,
            'ppda': self.ppda,
            'possession_pct': self.possession_pct,
            'pass_completion_pct': self.pass_completion_pct,
            'xg': self.xg,
            'shots': self.shots,
            'pressures': self.pressures,
        }


@dataclass
class MatchTacticalAnalysis:
    """Complete tactical analysis for all phases of a match."""
    home_team: str
    away_team: str
    phase_profiles: List[Dict[str, TacticalProfile]]  # per phase: {home_team: profile, away_team: profile}
    overall_home_profile: TacticalProfile = None
    overall_away_profile: TacticalProfile = None
    key_tactical_themes: List[str] = field(default_factory=list)

    # Ground truth metrics (used by Verifier)
    ground_truth: dict = field(default_factory=dict)


class TacticalClassifierAgent:
    """
    Agent 3: Tactical Classifier

    Responsibility: Apply structured classification rules to per-phase
    metrics to produce human-readable tactical labels.

    Classification is rule-based (deterministic) so the Verifier can
    always check: "You said High Press — PPDA was X. Is X < 8? Yes/No."

    The LLM's job here is to write the *narrative* connecting the numbers.
    The labels themselves come from the rules.
    """

    # Thresholds (all documented for transparency)
    PPDA_HIGH_PRESS = 8.0
    PPDA_MID_BLOCK = 12.0
    POSSESSION_DOMINANT = 55.0
    POSSESSION_SUBDUED = 45.0
    PASS_COMPLETION_SHORT = 83.0   # High completion = short/patient buildup
    PASS_COMPLETION_DIRECT = 72.0  # Low completion = more direct play
    XG_CLINICAL = 0.5             # xG per shot threshold for efficiency
    XG_WASTEFUL = 0.2

    def __init__(self, verbose: bool = True):
        self.verbose = verbose
        self.segmenter = PhaseSegmenterAgent(verbose=False)

    def _log(self, msg: str):
        if self.verbose:
            print(f"[Tactical Classifier] {msg}")

    def classify(self, segmentation: MatchSegmentation) -> MatchTacticalAnalysis:
        """Classify all phases and build complete tactical picture."""
        self._log(f"Classifying {len(segmentation.phases)} phases")

        phase_profiles = []
        ground_truth = {}

        for phase in segmentation.phases:
            home_profile = self._classify_team_in_phase(
                segmentation.home_team, phase, is_home=True
            )
            away_profile = self._classify_team_in_phase(
                segmentation.away_team, phase, is_home=False
            )
            phase_profiles.append({
                segmentation.home_team: home_profile,
                segmentation.away_team: away_profile,
            })

            # Build ground truth dict for Verifier
            ground_truth[phase.name] = {
                segmentation.home_team: phase.get_metrics_for_team(segmentation.home_team),
                segmentation.away_team: phase.get_metrics_for_team(segmentation.away_team),
            }

            self._log(f"  {phase.name}: {segmentation.home_team}={home_profile.pressing_style} | "
                      f"{segmentation.away_team}={away_profile.pressing_style}")

        # Overall profiles (full match)
        overall_metrics = segmentation.full_match_metrics
        overall_home = self._classify_from_metrics(
            segmentation.home_team, "Full Match", 0, 90,
            overall_metrics['home']
        )
        overall_away = self._classify_from_metrics(
            segmentation.away_team, "Full Match", 0, 90,
            overall_metrics['away']
        )

        # Ground truth for full match
        ground_truth['Full Match'] = {
            segmentation.home_team: overall_metrics['home'],
            segmentation.away_team: overall_metrics['away'],
        }

        themes = self._identify_key_themes(segmentation, phase_profiles)

        return MatchTacticalAnalysis(
            home_team=segmentation.home_team,
            away_team=segmentation.away_team,
            phase_profiles=phase_profiles,
            overall_home_profile=overall_home,
            overall_away_profile=overall_away,
            key_tactical_themes=themes,
            ground_truth=ground_truth,
        )

    def _classify_team_in_phase(
        self, team: str, phase: MatchPhase, is_home: bool
    ) -> TacticalProfile:
        metrics = phase.get_metrics_for_team(team)
        return self._classify_from_metrics(
            team, phase.name, phase.start_minute, phase.end_minute, metrics
        )

    def _classify_from_metrics(
        self, team: str, phase_name: str,
        start: int, end: int, metrics: dict
    ) -> TacticalProfile:
        """Apply all classification rules to produce labels."""
        ppda = metrics.get('ppda', 99.0)
        poss = metrics.get('possession_pct', 50.0)
        pass_comp = metrics.get('pass_completion_pct', 80.0)
        xg = metrics.get('xg', 0.0)
        shots = metrics.get('shots', 0)

        pressing_style = self._classify_pressing(ppda)
        buildup_pattern = self._classify_buildup(poss, pass_comp)
        territorial = self._classify_territorial(poss)
        xg_efficiency = self._classify_xg_efficiency(xg, shots)

        return TacticalProfile(
            team=team,
            phase_name=phase_name,
            start_minute=start,
            end_minute=end,
            pressing_style=pressing_style,
            buildup_pattern=buildup_pattern,
            territorial_dominance=territorial,
            xg_efficiency=xg_efficiency,
            ppda=ppda,
            possession_pct=poss,
            pass_completion_pct=pass_comp,
            xg=xg,
            shots=shots,
            pressures=metrics.get('pressures', 0),
        )

    def _classify_pressing(self, ppda: float) -> str:
        """
        PPDA-based press classification.
        Formula: opponent_passes_in_own_half / defensive_actions_in_opp_half
        Lower = more aggressive pressing.
        """
        if ppda < self.PPDA_HIGH_PRESS:
            return "High Press"
        elif ppda < self.PPDA_MID_BLOCK:
            return "Mid-Block"
        else:
            return "Deep Block"

    def _classify_buildup(self, possession: float, pass_completion: float) -> str:
        """
        Classify how a team builds out of defense.
        High possession + high completion = patient, short build.
        Low completion = more direct (long ball / vertical).
        """
        if possession > self.POSSESSION_DOMINANT and pass_completion > self.PASS_COMPLETION_SHORT:
            return "Short / Patient Build"
        elif pass_completion < self.PASS_COMPLETION_DIRECT:
            return "Direct / Long Ball"
        elif possession < self.POSSESSION_SUBDUED:
            return "Counter-Attacking"
        else:
            return "Mixed Build"

    def _classify_territorial(self, possession: float) -> str:
        if possession > self.POSSESSION_DOMINANT:
            return "Dominant"
        elif possession < self.POSSESSION_SUBDUED:
            return "Subdued"
        else:
            return "Balanced"

    def _classify_xg_efficiency(self, xg: float, shots: int) -> str:
        """
        Classify how efficiently a team is creating chances.
        xG per shot measures chance quality.
        """
        if shots == 0:
            return "No Shots"
        xg_per_shot = xg / shots
        if xg_per_shot > self.XG_CLINICAL:
            return "Clinical / High Quality Chances"
        elif xg_per_shot > self.XG_WASTEFUL:
            return "Average Chance Quality"
        else:
            return "Low Quality Chances"

    def _identify_key_themes(
        self,
        segmentation: MatchSegmentation,
        phase_profiles: List[Dict]
    ) -> List[str]:
        """
        Identify 3-5 high-level tactical themes across the full match.
        These inform the Writer's report structure.
        """
        themes = []
        home = segmentation.home_team
        away = segmentation.away_team

        # Check if pressing style changed significantly
        if len(phase_profiles) >= 2:
            first_home = phase_profiles[0].get(home)
            last_home = phase_profiles[-1].get(home)
            if first_home and last_home:
                if first_home.pressing_style != last_home.pressing_style:
                    themes.append(
                        f"{home} shifted from {first_home.pressing_style} to "
                        f"{last_home.pressing_style} as the match evolved"
                    )

        # Check possession dominance
        overall_home_poss = segmentation.full_match_metrics['home'].get('possession_pct', 50)
        if overall_home_poss > 58:
            themes.append(f"{home} controlled possession throughout ({overall_home_poss}%)")
        elif overall_home_poss < 42:
            themes.append(f"{away} dominated possession ({100 - overall_home_poss}%)")

        # xG vs actual goals
        home_xg = segmentation.full_match_metrics['home'].get('xg', 0)
        away_xg = segmentation.full_match_metrics['away'].get('xg', 0)
        themes.append(f"xG: {home} {home_xg:.2f} vs {away} {away_xg:.2f} — "
                      f"{'scoreline reflected chances' if abs(home_xg - away_xg) < 0.5 else 'xG tells a different story than the scoreline'}")

        # Key event context
        for event in segmentation.key_events:
            if event['type'] == 'Goal':
                themes.append(f"Pivotal moment: {event['description']} (xG: {event.get('xg', 0):.2f})")

        return themes[:5]  # Cap at 5 themes

    def get_structured_data_for_writer(
        self, analysis: MatchTacticalAnalysis, segmentation: MatchSegmentation
    ) -> dict:
        """
        Package everything the Writer needs in a single structured dict.
        This is the complete briefing document passed to the Writer Agent.
        """
        phases_data = []
        for i, (phase, profiles) in enumerate(
            zip(segmentation.phases, analysis.phase_profiles)
        ):
            phase_dict = {
                'name': phase.name,
                'minutes': f"{phase.start_minute}'–{phase.end_minute}'",
                'trigger': phase.trigger_event,
                'home_metrics': phase.get_metrics_for_team(segmentation.home_team),
                'away_metrics': phase.get_metrics_for_team(segmentation.away_team),
                'home_tactics': profiles.get(segmentation.home_team).to_dict() if segmentation.home_team in profiles else {},
                'away_tactics': profiles.get(segmentation.away_team).to_dict() if segmentation.away_team in profiles else {},
            }
            phases_data.append(phase_dict)

        return {
            'home_team': segmentation.home_team,
            'away_team': segmentation.away_team,
            'full_match_metrics': segmentation.full_match_metrics,
            'overall_home_tactics': analysis.overall_home_profile.to_dict() if analysis.overall_home_profile else {},
            'overall_away_tactics': analysis.overall_away_profile.to_dict() if analysis.overall_away_profile else {},
            'phases': phases_data,
            'key_events': segmentation.key_events,
            'key_tactical_themes': analysis.key_tactical_themes,
            'ground_truth': analysis.ground_truth,
        }
